# list of links to display on linktree
#   in this order

[[links]]
name = "website"
icon = ""
url = "https://alifeee.net/"

[[links]]
name = "email"
icon = "email"
url = "mailto:webserf@alifeee.net"

# blogs

[[links]]
name = "blog"
icon = ""
url = "https://blog.alifeee.co.uk/"

[[links]]
name = "notes"
icon = ""
url = "https://blog.alifeee.co.uk/notes/"

[[links]]
name = "weeknotes"
icon = ""
url = "https://weeknotes.alifeee.co.uk/"

[[links]]
name = "server"
icon = ""
url = "https://server.alifeee.net/"

# social media

[[links]]
name = "Mastodon"
icon = "mastodon"
url = "https://mastodon.social/@alifeee"

[[links]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/alifeeerenn"

[[links]]
name = "Discord"
icon = "discord"
url = ""

# messaging

[[links]]
name = "Telegram"
icon = "telegram"
url = "https://t.me/alifeeerenn"

[[links]]
name = "Signal"
icon = "signal"
url = "https://signal.me/#eu/kIgXWNVUkaOSiIeC_kGA1KGIi8kcNdQEnY7tEq3S9DaJHrvr3dZNtIkNaPqid1Py"

# tracking music/films/books

[[links]]
name = "Spotify"
icon = "spotify"
url = "https://open.spotify.com/user/alifeeerenn"

[[links]]
name = "Bookwyrm"
icon = "https://assets.ramblingreaders.org/images/logos/small_R58keIh.jpg"
url = "https://ramblingreaders.org/user/alifeee/"

[[links]]
name = "Movary"
icon = "movary"
url = "https://movary.alifeee.net/users/alifeee"

# misc

[[links]]
name = "YouTube"
icon = "youtube"
url = "https://youtube.com/@alifeeer.2187"

[[links]]
name = "Steam"
icon = "steam"
url = "https://steamcommunity.com/id/alifeee/"

[[links]]
name = "portfolio"
icon = ""
url = "https://alfierenn.dev/"

# coding

[[links]]
name = "GitHub"
icon = "github"
url = "https://github.com/alifeee/"

[[links]]
name = "Itch.io"
icon = "itch_io"
url = "https://alifeee.itch.io/"

[[links]]
name = "Downpour"
icon = "downpour"
url = "https://downpour.games/~alifeee"
