name: automated build scripts

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install markdown

      # sitemap
      - name: Make sitemap
        run: |
          python ./scripts/sitemap.py ./sitemap.html
      
      ## automatic pages
      # favourites page
      - name: make favourites page
        run: (cd favourites; ./build.sh)

      # commit anything that changed
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
