name: Node.js Testing

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.js"
      - "**.json"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.js"
      - "**.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
